# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 0, size: 0.03},
    {id: 1, size: 0.03},
    {id: 2, size: 0.02},
    {id: 3, size: 0.02},
    {id: 4, size: 0.02},
    {id: 5, size: 0.02},
    {id: 6, size: 0.02},
    {id: 7, size: 0.02},
    {id: 8, size: 0.02},
    {id: 9, size: 0.02},
    {id: 10, size: 0.02},
    {id: 11, size: 0.02},
    {id: 12, size: 0.02},
    {id: 13, size: 0.02},
    {id: 14, size: 0.02},
    {id: 15, size: 0.02},
    {id: 16, size: 0.02},
    {id: 17, size: 0.02},
    {id: 18, size: 0.02},
    {id: 19, size: 0.02},
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional

#tag_bundles:
#  [
#    {
#      name: 'Arm_Bundle',
#      layout:
#        [
#          {id: 0, size: 0.05, x: 0, y: 0, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
#          {id: 1, size: 0.05, x: -0.72, y: 0, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
#        ]
#    },
#  ]
